# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ranked_or_not
    - name: Build
      run: dotnet build --no-restore ranked_or_not
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: RankedOrNot
        path: \ranked_or_not\RankedOrNot.Window\bin\Debug\net8.0-windows
